name: linting testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Building a production project
        run: npm run build:prod
      - name: TS lintingof the production project
        run: npm run lint:ts
      - name: SCSS linting of the production project
        run: npm run lint:scss
      - name: Unit testing of the production project
        run: npm run test
