name: linting testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Building a production project
        run: npm run build:prod
        if: always()
  testin:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
    steps:
      - name: TS linting of the production project
        run: npm run lint:ts
        if: always()
      - name: SCSS linting of the production project
        if: always()
        run: npm run lint:scss
      - name: Unit testing of the production project
        run: npm run test
        if: always()
      - name: Building storybook for the production project
        run: npm run storybook:build
        if: always()
      - name: UI Screenshot testing of the production project
        run: npm run test:ui:ci
